package:
  name: vecxx
  version: 0.0.3

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - pybind11 >=2.5.0

  run:
    - python
    - numpy


test:
  imports:
    - vecxx
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  summary: vectorize some text
  license_file: LICENSE
